#This file stores configuration options for Iris, such as the currently active shaderpack
#Tue Jun 30 16:36:03 CST 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=
