Ponder.registry(event => {
    event.create([
        "mekanismgenerators:fission_reactor_casing",
        "mekanismgenerators:fission_reactor_port",
        "mekanismgenerators:fission_fuel_assembly",
        "mekanismgenerators:control_rod_assembly"])//为裂变反应堆外壳,将裂变反应堆端口,裂变燃料组件,控制棒组件加入本思索
        .scene(
            "kubejs:fission_reactor",
            "裂变反应堆的使用",
            "kubejs:mek_liebian",
            (scene) => {
                scene.scaleSceneView(0.8)
                scene.showBasePlate()//显示地板
                scene.idle(20)//延迟1秒显示
                scene.world.showSection([2,1,2,6,1,6],Direction.DOWN)//以从上方落下的方式显示212至616的方块
                scene.idle(10)
                scene.world.showSection([2,2,2,6,2,6],Direction.DOWN)//以从上方落下的方式显示222至626的方块
                scene.addKeyframe()
                scene.idle(10)
                scene.rotateCameraY(180)
                scene.idle(15)
                scene.overlay.showOutline("red",{},[3,2,6,3,2,6],65)
                scene.text(30,"这个是输出冷却剂模式的裂变反应堆端口",[3.5,2.5,6.5])
                scene.idle(35)
                scene.text(30,"它用于输出蒸气或过热的钠蒸汽",[3.5,2.5,6.5])
                scene.idle(35)
                scene.overlay.showOutline("red",{},[5,2,6,5,2,6],100)
                scene.text(30,"这个是输出废料模式的裂变反应堆端口",[5.5,2.5,6.5])
                scene.idle(35)
                scene.text(30,"它用于输出核废料",[5.5,2.5,6.5])
                scene.idle(35)
                scene.overlay.showOutline("red",{},[3,2,6,3,2,6],30)
                scene.text(30,"你需要通过手持调整器对反应堆端口潜行右键来获得它们")
                scene.idle(40)
                scene.rotateCameraY(180)
                scene.idle(10)
                scene.world.showSection([2,3,2,6,3,6],Direction.DOWN)//以从上方落下的方式显示232至636的方块
                scene.addKeyframe()
                scene.idle(10)
                scene.overlay.showOutline("red",{},[5,2,5,3,3,3],60)
                scene.text(30,"这个是裂变燃料组件",[4,3,4])
                scene.idle(35)
                scene.text(30,"整根根裂变燃料组件组件之间不能有断开的地方",[4,3,4])
                scene.idle(35)
                scene.world.showSection([2,4,2,6,4,6],Direction.DOWN)//以从上方落下的方式显示242至646的方块
                scene.addKeyframe()
                scene.idle(10)
                scene.overlay.showOutline("red",{},[5,4,5,3,4,3],90)
                scene.text(30,"这个是控制棒组件",[4,4.5,4])
                scene.idle(35)
                scene.text(30,"每根裂变燃料组件要求有且仅有一个控制棒组件",[4,4.5,4])
                scene.idle(35)
                scene.text(30,"并且控制棒组件必须位于所有裂变燃料组件上方",[4,4.5,4])
                scene.idle(30)
                scene.world.showSection([2,5,2,6,5,6],Direction.DOWN)//以从上方落下的方式显示252至656的方块
                scene.idle(20)
                scene.overlay.showOutline("red",{},[2,1,2,6,5,6],30)
                scene.addKeyframe()
                scene.text(30,"这是一个成型的裂变反应堆")
                scene.idle(35)
                scene.rotateCameraY(360)
                scene.text(40,"裂变反应堆的大小在3x4x3到18x18x18中间(x,y,z)")
                scene.idle(45)
                scene.text(50,"裂变反应堆的每条棱和每个顶点上的方块必须是裂变反应堆外壳")
                scene.idle(55)
                scene.text(70,"裂变反应堆的每个面上的方块必须是裂变反应堆外壳/强化玻璃/裂变反应堆端口/裂变反应堆逻辑适配器之一")
                scene.idle(75)
                scene.text(50,"裂变反应堆的内部的方块必须为空气/裂变燃料组件/控制棒组件之一")
                scene.idle(55)
                scene.text(50,"右键打开反应堆GUI后,在左上角统计信息中可以看到很多信息")
                scene.idle(55)
                scene.text(50,"其中,最为关键的是设置速率上限,更高的速率上限可以更快的产出核废料...")
                scene.idle(55)
                scene.text(50,"同时也会产生更高的温度,当温度超过1200K时.损坏率就会开始提升")
                scene.idle(55)
                scene.text(50,"而一旦损坏率达到100%...反应堆每t都会有熔毁的可能性,损坏率越高熔毁的概率越大")
                scene.idle(55)
                scene.addKeyframe()
                scene.overlay.showOutline("red",{},[5,2,2,5,2,2],240)
                scene.overlay.showOutline("red",{},[3,2,2,3,2,2],240)
                scene.text(90,"你需要通过仅输入模式的裂变反应堆端口向成型的裂变反应堆输入裂变燃料与冷却剂",[4,2,2])
                scene.idle(95)
                scene.text(50,"其中,可选的冷却剂有水和钠蒸汽",[4,2,2])
                scene.idle(55)
                scene.text(120,"你知道吗,钠蒸汽的极限速率为水的2倍,不过因为种种原因,钠蒸汽极少人用,但是好在本包的创造化学品储罐解决了所有麻烦,你可以非常舒服的使用钠蒸汽进行冷却并将过热的钠蒸汽直接销毁",[4,2,2])
            }
        )
})